---
apiVersion: v2
name: clabernetes
description: Manage containerlab topologies in a kubernetes cluster
home: https://github.com/srl-labs/clabernetes
sources:
  - https://github.com/srl-labs/clabernetes
keywords:
  - network
  - containerlab
maintainers:
  - name: Carl Montanari
    email: carl.r.montanari@gmail.com
    url: https://twitter.com/carlrmontanari
type: application
version: 0.0.11
dependencies: []
