---
apiVersion: v1
kind: Secret
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    clabernetes/app: {{ .Values.appName }}
    clabernetes/name: "{{ .Values.appName }}-certificate"
    clabernetes/component: certificate
    clabernetes/part-of: manager
  name: "{{ .Values.appName }}-certificate"
data: {}