---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    clabernetes/app: {{ .Values.appName }}
    clabernetes/name: "{{ .Values.appName }}-clicker-cluster-role"
    clabernetes/component: cluster-role
  name: "{{ .Values.appName }}-clicker-cluster-role"
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - create
      - watch
      - delete