---
{{ if not .Values.cron.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appName }}-clicker
  namespace: {{ .Release.Namespace }}
{{ include "jobMetadata" . | indent 2 }}
spec:
  template:
    metadata:
{{ include "jobMetadata" . | indent 6 }}
    spec:
      containers:
{{ include "jobContainer" . | indent 8 }}
      restartPolicy: Never
      serviceAccountName: "{{ .Values.appName }}-clicker-service-account"
  backoffLimit: 4
  ttlSecondsAfterFinished: 300
{{- end }}