---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.appName }}-clicker-service-account"
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    revision: "{{ .Release.Revision }}"
    clabernetes/app: {{ .Values.appName }}
    clabernetes/name: "{{ .Values.appName }}-clicker-service-account"
    clabernetes/component: service-account
    {{- if .Values.globalLabels }}
{{ .Values.globalLabels | toYaml | indent 4 }}
    {{- end }}
  {{- if .Values.globalAnnotations }}
  annotations:
{{ .Values.globalAnnotations | toYaml | indent 4 }}
  {{- end }}