apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Connectivity
metadata:
  labels:
    clabernetes/app: clabernetes
    clabernetes/name: topology-basic
    clabernetes/topologyKind: containerlab
    clabernetes/topologyOwner: topology-basic
  name: topology-basic
  namespace: NAMESPACE
  ownerReferences:
    - apiVersion: clabernetes.containerlab.dev/v1alpha1
      kind: Topology
      name: topology-basic
spec:
  pointToPointTunnels: {}
status: {}
