---
apiVersion: topology.clabernetes/v1alpha1
kind: Containerlab
metadata:
  name: srl02
  namespace: notclabernetes
spec:
  insecureRegistries:
    - 1.2.3.4
  filesFromConfigMap:
      srl1:
        - filePath: srl1.cfg
          configMapName: srl02-srl1-startup-config
          configMapPath: startup-config
        - filePath: taco/srl1.license
          configMapName: srl02-srl1-files
          configMapPath: taco-srl1.license
      srl2:
        - filePath: /Users/carl/dev/github/clabernetes/clabverter/test-fixtures/clabversiontest/srl2/potato.txt
          configMapName: srl02-srl2-files
          configMapPath: Users-carl-dev-github-clabernetes-clabverter-test-fixt-812fc54
        - filePath: /Users/carl/dev/github/clabernetes/clabverter/test-fixtures/clabversiontest/potato.txt
          configMapName: srl02-srl2-files
          configMapPath: Users-carl-dev-github-clabernetes-clabverter-test-fixt-d1c1dd8
        - filePath: srl2.license
          configMapName: srl02-srl2-files
          configMapPath: srl2.license
        - filePath: srl2.cfg
          configMapName: srl02-srl2-startup-config
          configMapPath: startup-config

  config: |-
    name: srl02

    topology:
      nodes:
        srl1:
          kind: srl
          image: ghcr.io/nokia/srlinux
          startup-config: srl1.cfg
          license: taco/srl1.license
        srl2:
          kind: srl
          image: ghcr.io/nokia/srlinux
          startup-config: srl2.cfg
          license: srl2.license
          binds:
            - __clabDir__/potato.txt:/potato.txt
            - __clabNodeDir__/potato.txt:/nodedir-potato.txt

      links:
        - endpoints: ["srl1:e1-1", "srl2:e1-1"]
