---
apiVersion: v2
name: clicker
description: Cl(aberntes t)ick(l)er! For "clicking" on some nodes to perform clabernetes related cluster wide sysctl commands.
home: https://github.com/srl-labs/clabernetes
sources:
  - https://github.com/srl-labs/clabernetes
keywords:
  - network
  - containerlab
maintainers:
  - name: Carl Montanari
    email: carl.r.montanari@gmail.com
    url: https://twitter.com/carlrmontanari
type: application
version: 0.0.15
dependencies: []