---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clabernetes-manager
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    clabernetes/app: {{ .Values.appName }}
    clabernetes/name: "{{ .Values.appName }}-cluster-role-binding"
    clabernetes/component: cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.appName }}-service-account"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: "{{ .Values.appName }}-cluster-role"
  apiGroup: rbac.authorization.k8s.io