---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    clabernetes/app: {{ .Values.appName }}
    clabernetes/name: "{{ .Values.appName }}-config"
    clabernetes/component: config
    {{- if .Values.globalLabels }}
{{ .Values.globalLabels | toYaml | indent 4 }}
    {{- end }}
  {{- if .Values.globalAnnotations }}
  annotations:
{{ .Values.globalAnnotations | toYaml | indent 4 }}
  {{- end }}
data:
  globalAnnotations: |-
    ---
{{ .Values.globalAnnotations | toYaml | indent 4 }}
  globalLabels: |-
    ---
{{ .Values.globalLabels | toYaml | indent 4 }}
  defaultResources: |-
    ---
{{ .Values.launcher.defaultResources | toYaml | indent 4 }}
