{{- if .Values.globalConfig.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    revision: "{{ .Release.Revision }}"
    clabernetes/app: {{ .Values.appName }}
    clabernetes/name: "{{ .Values.appName }}-config"
    clabernetes/component: config
    {{- if .Values.globalLabels }}
{{ .Values.globalLabels | toYaml | indent 4 }}
    {{- end }}
  {{- if .Values.globalAnnotations }}
  annotations:
{{ .Values.globalAnnotations | toYaml | indent 4 }}
  {{- end }}
data:
  mergeMode: {{ .Values.globalConfig.mergeMode }}
  globalAnnotations: |-
    ---
{{ .Values.globalAnnotations | toYaml | indent 4 }}
  globalLabels: |-
    ---
{{ .Values.globalLabels | toYaml | indent 4 }}
  resourcesDefault: |-
    ---
{{ .Values.globalConfig.deployment.resourcesDefault | toYaml | indent 4 }}
  resourcesByContainerlabKind: |-
    ---
{{ .Values.globalConfig.deployment.resourcesByContainerlabKind | toYaml | indent 4 }}
  inClusterDNSSuffix: {{ .Values.globalConfig.inClusterDNSSuffix }}
  imagePullThroughMode: {{ .Values.globalConfig.imagePull.imagePullThroughMode }}
{{- end }}