---
name: lint

on:
  workflow_call: {}
  workflow_dispatch: {}

env:
  GO_VERSION: "1.21"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: ensure go mod is tidy
        run: |
          git diff --exit-code --name-only go.mod go.sum 2>&1

      - name: install go lint tools
        run: |
          go install mvdan.cc/gofumpt@${{ vars.GOFUMPT_VERSION }}
          go install github.com/daixiang0/gci@${{ vars.GCI_VERSION }}
          go install github.com/segmentio/golines@${{ vars.GOLINES_VERSION }}
          curl -sSfL \
            https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
            sh -s -- -b $(go env GOPATH)/bin ${{ vars.GOLANGCI_LINT_VERSION }}

      - name: run the linter
        run: make lint
